const sample_users = [
  {
    id: "1",
    firstName: "Pierre",
    secondName: "Andrés",
    lastName: "Julliard Amador",
    birthDate: new Date("1970-11-06"),
    gender: "Masculino",
    email: "pierre.andres@gmail.com",
    phone: "3118005871",
    documentNumber: "72333444",
    documentType: "Cédula",
    profilePicture: "profile.jpg",
    toponymy: "El nombre 'Pierre' es de origen francés y significa 'piedra' o 'roca', símbolo de fuerza y estabilidad. Es una variante del nombre Pedro, muy común en Francia y otros países francófonos.",
    isAdmin: false,
  },
  {
    id: "2",
    firstName: "María",
    secondName: "Elena",
    lastName: "Ramírez López",
    birthDate: new Date("1985-03-15"),
    gender: "Femenino",
    email: "maria.elena@gmail.com",
    phone: "3104567890",
    documentNumber: "1023456789",
    documentType: "Cédula",
    profilePicture: "profile.jpg",
    toponymy: "El nombre 'María' es de origen hebreo y significa 'la elegida' o 'la amada de Dios'. Es uno de los nombres más comunes en el mundo, especialmente en países de tradición cristiana.",
    isAdmin: true,
  },
  {
    id: "3",
    firstName: "Carlos",
    secondName: "Alberto",
    lastName: "García Pérez",
    birthDate: new Date("1990-07-22"),
    gender: "No binario",
    email: "carlos.alberto@gmail.com",
    phone: "3001234567",
    documentNumber: "9876543210",
    documentType: "Cédula",
    profilePicture: "profile.jpg",
    toponymy: "El nombre 'Carlos' tiene raíces germánicas y significa 'hombre libre'. Fue popularizado por la realeza europea y es común en países de habla hispana.",
    isAdmin: false,
  },
  {
    id: "4",
    firstName: "Lucía",
    secondName: "Fernanda",
    lastName: "Martínez Gómez",
    birthDate: new Date("1995-12-02"),
    gender: "Femenino",
    email: "lucia.fernanda@gmail.com",
    phone: "3201239876",
    documentNumber: "1012345678",
    documentType: "Tarjeta de identidad",
    profilePicture: "profile.jpg",
    toponymy: "El nombre 'Lucía' proviene del latín 'lux', que significa 'luz'. Es un nombre que simboliza claridad y esperanza, y es popular en varios países de habla hispana.",
    isAdmin: false,
  },
  {
    id: "5",
    firstName: "Juan",
    secondName: "Pablo",
    lastName: "Hernández Torres",
    birthDate: new Date("1998-05-10"),
    gender: "Masculino",
    email: "juan.pablo@gmail.com",
    phone: "3156789123",
    documentNumber: "1034567890",
    documentType: "Cédula",
    profilePicture: "profile.jpg",
    toponymy: "El nombre 'Juan' es de origen hebreo y significa 'Dios es misericordioso'. Es uno de los nombres más difundidos en el mundo, especialmente en contextos religiosos.",
    isAdmin: true,
  },
];

// Exportar con CommonJS
module.exports = { sample_users };
