const sample_users = [
  {
    id: "1",
    firstName: "Pierre",
    secondName: "Andrés",
    lastName: "Julliard Amador",
    birthDate: "1970-11-06",
    gender: "Masculino",
    email: "pierre.andres@gmail.com",
    phone: "3118005871",
    documentNumber: "72333444",
    documentType: "Cédula",
    isAdmin: false,
  },
  {
    id: "2",
    firstName: "María",
    secondName: "Elena",
    lastName: "Ramírez López",
    birthDate: "1985-03-15",
    gender: "Femenino",
    email: "maria.elena@gmail.com",
    phone: "3104567890",
    documentNumber: "1023456789",
    documentType: "Cédula",
    isAdmin: true,
  },
  {
    id: "3",
    firstName: "Carlos",
    secondName: "Alberto",
    lastName: "García Pérez",
    birthDate: "1990-07-22",
    gender: "No binario",
    email: "carlos.alberto@gmail.com",
    phone: "3001234567",
    documentNumber: "9876543210",
    documentType: "Cédula",
    isAdmin: false,
  },
  {
    id: "4",
    firstName: "Lucía",
    secondName: "Fernanda",
    lastName: "Martínez Gómez",
    birthDate: "1995-12-02",
    gender: "Femenino",
    email: "lucia.fernanda@gmail.com",
    phone: "3201239876",
    documentNumber: "1012345678",
    documentType: "Tarjeta de identidad",
    isAdmin: false,
  },
  {
    id: "5",
    firstName: "Juan",
    secondName: "Pablo",
    lastName: "Hernández Torres",
    birthDate: "1998-05-10",
    gender: "Masculino",
    email: "juan.pablo@gmail.com",
    phone: "3156789123",
    documentNumber: "1034567890",
    documentType: "Cédula",
    isAdmin: true,
  },
];

// Exportar con CommonJS
module.exports = { sample_users };
